FROM node:18.10.0-slim

WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY ./db ./db
COPY ./routes ./routes
COPY ./server.js ./server.js

ENV NODE_ENV production

ENV MONGODB_URI mongodb://mongodb:27017/default
ENV PORT 8080
ENV SECRET secret
EXPOSE ${PORT}

USER node

CMD [ "node", "server.js" ]